# Generated by Django 5.1.6 on 2025-03-19 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('networks', '0002_usernetwork_usersubnet_delete_network'),
    ]

    operations = [
        migrations.AddField(
            model_name='usernetwork',
            name='ssh_password',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
