# Generated by Django 5.1.6 on 2025-04-11 12:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('networks', '0005_userip'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserDeployedNetworks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('free5G_deployed', models.BooleanField(default=False)),
                ('core5G_deployed', models.BooleanField(default=False)),
                ('gen_deployed', models.BooleanField(default=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deployed_networks', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
