# Generated by Django 5.1.6 on 2025-04-11 19:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('networks', '0006_userdeployednetworks'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userdeployednetworks',
            old_name='core5G_deployed',
            new_name='open5G_deployed',
        ),
    ]
