# Generated by Django 5.1.6 on 2025-04-27 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('networks', '0007_rename_core5g_deployed_userdeployednetworks_open5g_deployed'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ssh_password',
            options={'verbose_name': 'SSH password', 'verbose_name_plural': 'SSH passwords'},
        ),
        migrations.AlterModelOptions(
            name='userdeployednetworks',
            options={'verbose_name': 'User deployed network', 'verbose_name_plural': 'User deployed networks'},
        ),
        migrations.AlterModelOptions(
            name='userip',
            options={'verbose_name': 'User IP', 'verbose_name_plural': 'User IPs'},
        ),
        migrations.AlterModelOptions(
            name='usernetwork',
            options={'verbose_name': 'User network', 'verbose_name_plural': 'User networks'},
        ),
        migrations.AlterModelOptions(
            name='usersubnet',
            options={'verbose_name': 'User subnet', 'verbose_name_plural': 'User subnets'},
        ),
        migrations.AddField(
            model_name='ssh_password',
            name='type',
            field=models.CharField(default='password', max_length=50),
        ),
        migrations.AlterField(
            model_name='ssh_password',
            name='ssh_password',
            field=models.CharField(max_length=50),
        ),
    ]
