# Generated by Django 5.1.6 on 2025-05-06 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('networks', '0008_alter_ssh_password_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userdeployednetworks',
            name='free5G_error',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='userdeployednetworks',
            name='gen_error',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='userdeployednetworks',
            name='open5G_error',
            field=models.BooleanField(default=False),
        ),
    ]
